### ISSUE TITLE
Unresolved import `crate::test_utils::find_vector`

### ISSUE THREAD

**Issue by mattsse** [nomad-xyz/rust#118]
This function does not exist but is imported and used 

https://github.com/nomad-xyz/rust/blob/59282f65da4748352f2ec7e129c575b58e43f1ed/nomad-core/src/test_output.rs#L6

**Comment by lattejed** [comment]
Currently using `cargo test` in the contrib guidelines and in the workflows which misses this as it's behind a feature flag. 

A stricter `cargo test --workspace --all-features` or something more appropriate will throw an error here correctly.

@prestwich @ltchang2019 has this been relaxed in the workflow (vs. the monorepo's pre-commit script) on purpose or should this be updated? 

I'd also recommend updating the contrib guidelines to match to prevent round-tripping on missed errors.

Let me know if this makes sense and I'll assign myself.

**Comment by prestwich** [comment]
We did not intentionally relax this. Let's get stricter and add it to contrib guidelines :)
