### ISSUE TITLE
feat(agents): improve agent config

### ISSUE THREAD

**Issue by lattejed** [nomad-xyz/rust#169]
Agent config should be improved to speed up deployments. Currently most config changes have to go through a PR->deploy cycle. Configs should be updatable after deployment

- [x] Agent config should be simplified with sensible defaults
- [x] All necessary settings should be overridable with env vars

This touches or umbrellas some existing issues:

https://github.com/nomad-xyz/rust/issues/149
https://github.com/nomad-xyz/rust/issues/159
https://github.com/nomad-xyz/rust/issues/81

Context / more info:

https://github.com/nomad-xyz/rust/issues/148 (https://github.com/nomad-xyz/rust/pull/140/commits/56c4807b130ec620f47cee51cc1219197c050fde)
https://github.com/nomad-xyz/rust/issues/135
https://github.com/nomad-xyz/rust/issues/40
https://github.com/nomad-xyz/rust/issues/39
https://github.com/nomad-xyz/rust/issues/34

**Comment by ltchang2019** [comment]
> More config info here: https://docs.nomad.xyz/dev/agents/agent-development.html

These are unfortunately stale :( working on updating for external operators

**Comment by lattejed** [comment]
#171 covers only part of this, so I'm going to keep this open
