### ISSUE TITLE
replace `strip_0x_prefix` with use of the std lib method

### ISSUE THREAD

**Issue by prestwich** [nomad-xyz/rust#32]
https://doc.rust-lang.org/std/string/struct.String.html#method.strip_prefix

this was standardized sometime after we wrote the `strip_0x_prefix` method

**Comment by lattejed** [comment]
@ltchang2019 looks like you replaced the usages of `strip_0x_prefix` but left the fn in `nomad-types/src/utils.rs`

Is there any reason to keep it around? If not, would you mind nuking it?

**Comment by ltchang2019** [comment]
Yep feel free to remove it, thanks @lattejed :)
